// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IAnalysisService is an autogenerated mock type for the IAnalysisService type
type IAnalysisService struct {
	mock.Mock
}

// FindEmails provides a mock function with given fields: input
func (_m *IAnalysisService) FindEmails(input string) []string {
	ret := _m.Called(input)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewIAnalysisService creates a new instance of IAnalysisService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAnalysisService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAnalysisService {
	mock := &IAnalysisService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
